source $VIM_HOME/configs/base_config.vim
source $VIM_HOME/configs/plugin-manager.vim
source $VIM_HOME/configs/nerdtree-config.vim
source $VIM_HOME/configs/fzf-config.vim
source $VIM_HOME/configs/hybrid-line-number.vim
source $VIM_HOME/configs/lightline-config.vim
source $VIM_HOME/configs/startify-config.vim
source $VIM_HOME/configs/python-config.vim

" Move to colorscheme.vim
set background=dark
colorscheme molokai

imap jj <ESC>

nnoremap <leader>vc :so $MYVIMRC<CR>

set wildignore+=**/node_modules/**
nnoremap <C-q> :close<CR>
nnoremap <C-e> :tabedit %<CR>
highlight StatusLineNC cterm=bold ctermfg=white ctermbg=darkgray

nnoremap <leader>r :checktime<CR>

inoremap <C-a> <C-o>a

augroup BgHighlight
    autocmd!
    autocmd WinEnter * set relativenumber
    autocmd WinLeave * set norelativenumber
augroup END

augroup BgHighlight
    autocmd!
    autocmd WinEnter * set colorcolumn=120
    autocmd WinLeave * set colorcolumn=0
augroup END

augroup CursorLineOnlyInActiveWindow
  autocmd!
  autocmd VimEnter,WinEnter,BufWinEnter * setlocal cursorline
augroup END
  autocmd WinLeave * setlocal nocursorline

hi Visual term=reverse cterm=reverse

autocmd BufEnter * :syntax sync fromstart

let @/ = ""

hi MatchParen ctermfg=208 ctermbg=bg

set splitbelow
set splitright
