# Adding Tmux session
export DOTFILES_HOME="$HOME/.dotfiles"
export ZSH_HOME="$DOTFILES_HOME/zsh"
export TMUX_HOME="$DOTFILES_HOME/tmux"
export VIM_HOME="$DOTFILES_HOME/vim"
export VIM_PLUGINS="$VIM_HOME/plugins"
export ZPLUGIN="$ZSH_HOME/zplugin/bin"

declare -A ZPLGM

export ZPLGM[HOME_DIR]="$ZSH_HOME/zplugin"


source $ZPLUGIN/zplugin.zsh

zplugin ice blockf
zplugin light zsh-users/zsh-syntax-highlighting
zplugin light romkatv/powerlevel10k

zplugin ice svn
zplugin snippet OMZ::plugins/z

zplugin snippet "https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh"


zplugin ice blockf \
atpull'zplg creinstall zsh-users/zsh-completions'
zplugin light zsh-users/zsh-completions


autoload -Uz compinit

for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C

zplugin cdreplay -q


for file in $ZSH_HOME/custom/**/*.zsh; do
	source $file
done

export TERM=screen-256color

if [ -z "$TMUX" ] && [ -z "$DISPLAY" ]; then
		exec tmux
fi

# NPM Global config
npm config set prefix '~/.npm-global'

export PATH=~/.npm-global/bin:$PATH

export PATH=~/anaconda3/bin:$PATH

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias intent_login="ssh -i $HOME/amazon_keys/intent.pem ubuntu@ec2-3-136-64-162.us-east-2.compute.amazonaws.com"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/kirangadhave/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/kirangadhave/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/kirangadhave/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/kirangadhave/google-cloud-sdk/completion.zsh.inc'; fi
