# Adding Tmux session
export DOTFILES_HOME="$HOME/.dotfiles"
export ZSH_HOME="$DOTFILES_HOME/zsh"
export TMUX_HOME="$DOTFILES_HOME/tmux"
export ZPLUGIN="$ZSH_HOME/zplugin/bin"

declare -A ZPLGM

export ZPLGM[HOME_DIR]="$ZSH_HOME/zplugin"

if [ -z "$TMUX" ] && [ -z "$DISPLAY" ]; then
	if tmux has-session; then
		exec tmux attach-session
	else
		exec tmux
	fi
fi

source $ZPLUGIN/zplugin.zsh

zplugin light zsh-users/zsh-syntax-highlighting